spring:
  application:
    name: security-service
  datasource:
    url: jdbc:h2:mem:auth-db
    driver-class-name: org.h2.Driver
    username: root
    password: auth
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${EUREKA_HOST:localhost}:8761/eureka
    instance:
      hostname: Authorization-Server

server:
  port: 8091

keyStore:
  path: keystore.jks
  password: password