spring:
  application:
    name: security-service
  datasource:
    username: root
    password: backend
    url: jdbc:mysql://${DB_SERVER:localhost}:3306/${DB_NAME:users}?createDatabaseIfNotExists=true&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
    instance:
      hostname: security-service

server:
  port: 8091

keyStore:
  path: keystore.jks
  password: password
  alias: auth-server